import 'CandidatModel.dart';

final List<CompetenceModel> competenceModels = [
  CompetenceModel(label: "Programmation", value: "programmation"),
  CompetenceModel(label: "Python", value: "python"),
  CompetenceModel(label: "PHP", value: "php"),
  CompetenceModel(label: "JavaScript", value: "javascript"),
  CompetenceModel(label: "Java", value: "java"),
  CompetenceModel(label: "C#", value: "csharp"),
  CompetenceModel(label: "Ruby", value: "ruby"),
  CompetenceModel(label: "HTML", value: "html"),
  CompetenceModel(label: "CSS", value: "css"),
  CompetenceModel(label: "SQL", value: "sql"),
  CompetenceModel(label: "Swift", value: "swift"),
  CompetenceModel(label: "TypeScript", value: "typescript"),
  CompetenceModel(label: "Go", value: "go"),
  CompetenceModel(label: "Rust", value: "rust"),
  CompetenceModel(label: "Kotlin", value: "kotlin"),
  CompetenceModel(label: "Dart", value: "dart"),
  CompetenceModel(label: "Design graphique", value: "design_graphique"),
  CompetenceModel(label: "Graphisme", value: "graphisme"),
  CompetenceModel(label: "Design Web", value: "designWeb"),
  CompetenceModel(label: "Branding", value: "branding"),
  CompetenceModel(label: "Marketing Digital", value: "marketingDigital"),
  CompetenceModel(label: "Illustration", value: "illustration"),
  CompetenceModel(label: "Stratégie Marketing", value: "strategieMarketing"),
  CompetenceModel(label: "Gestion de Projet", value: "gestionProjet"),
  CompetenceModel(label: "Communication Visuelle", value: "communicationVisuelle"),
  CompetenceModel(label: "Analyse de Marché", value: "analyseMarche"),
  CompetenceModel(label: "Publicité", value: "publicite"),
  CompetenceModel(label: "Marketing", value: "marketing"),
  CompetenceModel(label: "Rédaction de contenu", value: "redaction_contenu"),
  CompetenceModel(label: "Gestion de projet", value: "gestion_projet"),
  CompetenceModel(label: "Analyse de données", value: "analyse_donnees"),
  CompetenceModel(label: "Communication", value: "communication"),
  CompetenceModel(label: "Vente", value: "vente"),
  CompetenceModel(label: "Relation client", value: "relation_client"),
  CompetenceModel(label: "Développement web", value: "developpement_web"),
  CompetenceModel(label: "Administration système", value: "administration_systeme"),
  CompetenceModel(label: "Réseaux et sécurité", value: "reseaux_securite"),
  CompetenceModel(label: "Gestion financière", value: "gestion_financiere"),
  CompetenceModel(label: "Comptabilité Générale", value: "comptabiliteGenerale"),
  CompetenceModel(label: "Fiscalité", value: "fiscalite"),
  CompetenceModel(label: "Audit", value: "audit"),
  CompetenceModel(label: "Gestion Budgétaire", value: "gestionBudgetaire"),
  CompetenceModel(label: "Analyse Financière", value: "analyseFinanciere"),
  CompetenceModel(label: "Gestion de Trésorerie", value: "gestionTresorerie"),
  CompetenceModel(label: "Rapports Financiers", value: "rapportsFinanciers"),
  CompetenceModel(label: "Gestion des Comptes Clients", value: "gestionComptesClients"),
  CompetenceModel(label: "Gestion des Comptes Fournisseurs", value: "gestionComptesFournisseurs"),
  CompetenceModel(label: "Logiciels de Comptabilité", value: "logicielsComptabilite"),
  CompetenceModel(label: "Langues étrangères", value: "langues_etrangeres"),
  CompetenceModel(label: "Service client", value: "service_client"),
  CompetenceModel(label: "Développement mobile", value: "developpement_mobile"),
  CompetenceModel(label: "Analyse fonctionnelle", value: "analyse_fonctionnelle"),
  CompetenceModel(label: "Architecture logicielle", value: "architecture_logicielle"),
  CompetenceModel(label: "UX/UI design", value: "ux_ui_design"),
  CompetenceModel(label: "Management", value: "management"),
  CompetenceModel(label: "Audit et conseil", value: "audit_conseil"),
  CompetenceModel(label: "Logistique et supply chain", value: "logistique_supply_chain"),
  CompetenceModel(label: "Santé et sécurité au travail", value: "sante_securite_travail"),
  CompetenceModel(label: "Enseignement", value: "enseignement"),
  CompetenceModel(label: "Développement durable", value: "developpement_durable"),
  CompetenceModel(label: "Journalisme", value: "journalisme"),
  CompetenceModel(label: "Traduction", value: "traduction"),
  CompetenceModel(label: "Design industriel", value: "design_industriel"),
  CompetenceModel(label: "Art et culture", value: "art_culture"),
];
