

export const localites = [
    { label: 'Abengourou', value: 'abengourou' },
    { label: 'Abidjan', value: 'abidjan' },
    { label: 'Aboisso', value: 'aboisso' },
    { label: 'Adzopé', value: 'adzope' },
    { label: 'Agboville', value: 'agboville' },
    { label: 'Akoupé', value: 'akoupe' },
    { label: 'Anyama', value: 'anyama' },
    { label: 'Bondoukou', value: 'bondoukou' },
    { label: 'Bouaflé', value: 'bouafle' },
    { label: 'Bouna', value: 'bouna' },
    { label: 'Boundiali', value: 'boundiali' },
    { label: 'Dabou', value: 'dabou' },
    { label: 'Daloa', value: 'daloa' },
    { label: 'Danané', value: 'danane' },
    { label: 'Daoukro', value: 'daoukro' },
    { label: 'Dimbokro', value: 'dimbokro' },
    { label: 'Divo', value: 'divo' },
    { label: 'Duékoué', value: 'duekoue' },
    { label: 'Ferkessédougou', value: 'ferkessedougou' },
    { label: 'Gagnoa', value: 'gagnoa' },
    { label: 'Grand-Bassam', value: 'grand-bassam' },
    { label: 'Guiglo', value: 'guiglo' },
    { label: 'Issia', value: 'issia' },
    { label: 'Katiola', value: 'katiola' },
    { label: 'Korhogo', value: 'korhogo' },
    { label: 'Lakota', value: 'lakota' },
    { label: 'Man', value: 'man' },
    { label: 'Odienné', value: 'odienne' },
    { label: 'San-Pédro', value: 'san-pedro' },
    { label: 'Sassandra', value: 'sassandra' },
    { label: 'Séguéla', value: 'seguela' },
    { label: 'Soubré', value: 'soubre' },
    { label: 'Tiassalé', value: 'tiassale' },
    { label: 'Tingréla', value: 'tingrela' },
    { label: 'Toumodi', value: 'toumodi' },
    { label: 'Vavoua', value: 'vavoua' },
    { label: 'Yamoussoukro', value: 'yamoussoukro' },
    { label: 'Zuénoula', value: 'zuenoula' },
  ];
  