export const optionPays = [
    { label: "Algérie", value: "Algeria" },
    { label: "Angola", value: "Angola" },
    { label: "Bénin", value: "Benin" },
    { label: "Botswana", value: "Botswana" },
    { label: "Burkina Faso", value: "Burkina Faso" },
    { label: "Burundi", value: "Burundi" },
    { label: "Cameroun", value: "Cameroon" },
    { label: "Cap-Vert", value: "Cape Verde" },
    { label: "République centrafricaine", value: "Central African Republic" },
    { label: "Tchad", value: "Chad" },
    { label: "Comores", value: "Comoros" },
    { label: "République du Congo", value: "Congo (Republic of the)" },
    { label: "République démocratique du Congo", value: "Congo (Democratic Republic of the)" },
    { label: "Côte d'Ivoire", value: "Cote d'Ivoire" },
    { label: "Djibouti", value: "Djibouti" },
    { label: "Égypte", value: "Egypt" },
    { label: "Guinée équatoriale", value: "Equatorial Guinea" },
    { label: "Érythrée", value: "Eritrea" },
    { label: "Éthiopie", value: "Ethiopia" },
    { label: "Gabon", value: "Gabon" },
    { label: "Gambie", value: "Gambia" },
    { label: "Ghana", value: "Ghana" },
    { label: "Guinée", value: "Guinea" },
    { label: "Guinée-Bissau", value: "Guinea-Bissau" },
    { label: "Kenya", value: "Kenya" },
    { label: "Lesotho", value: "Lesotho" },
    { label: "Liberia", value: "Liberia" },
    { label: "Libye", value: "Libya" },
    { label: "Madagascar", value: "Madagascar" },
    { label: "Malawi", value: "Malawi" },
    { label: "Mali", value: "Mali" },
    { label: "Mauritanie", value: "Mauritania" },
    { label: "Maurice", value: "Mauritius" },
    { label: "Maroc", value: "Morocco" },
    { label: "Mozambique", value: "Mozambique" },
    { label: "Namibie", value: "Namibia" },
    { label: "Niger", value: "Niger" },
    { label: "Nigeria", value: "Nigeria" },
    { label: "Rwanda", value: "Rwanda" },
    { label: "São Tomé et Príncipe", value: "Sao Tome and Principe" },
    { label: "Sénégal", value: "Senegal" },
    { label: "Seychelles", value: "Seychelles" }
];
  


